config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#home"

  resources "questions", :only => ["create", "show"] do
    post "answer/:answer_id", :to => "questions#answer", :as => "answer"
  end

  get "/games/:game_id" => "home#home", :as => "game"

  resources "rounds", :only => ["show"]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :rounds
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  scope :correct, -> { where(correct: true) }
  scope :incorrect, -> { where(correct: false) }
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  belongs_to :round
  validates_presence_of :prompt

  def self.create_from_json(params, round)
    params = params.symbolize_keys if params.respond_to?(:symbolize_keys)
    question = Question.create!(
      :prompt => params[:question],
      :round => round,
    )

    ["A", "B", "C", "D"].each do |letter|
      Option.create!(
        :prompt => params[letter.to_sym],
        :question => question,
        :correct => (params[:answer] == letter)
      )
    end

    question
  end

  def answer
    options.correct.first!
  end

  def answered?(user)
    UserAnswer.where(:user => user, :question => self).count > 0
  end
end

app/models/round.rb
class Round < ApplicationRecord
  has_many :questions, dependent: :destroy
  belongs_to :game
	validates_presence_of :game_id
  before_save :set_label

  def self.questions_per_round
    if Rails.env.production?
      20
    else
      5
    end
  end

  def answered_questions(user)
    return @_answered_questions if defined?(@_answered_questions)
    @_answered_questions = UserAnswer.where(
      :user_id => user.id,
      :question_id => questions.map(&:id)
    )
  end

  def next_question(user)
    question_ids_left = questions.map(&:id) - answered_questions(user).map(&:question_id)

    if question_ids_left.length > 0
      Question.find(question_ids_left[0])
    end
  end

  private

  def set_label
    if self.label.nil?
      self.label = "Round #{game.rounds.count + 1}"
    end
  end
end

app/models/stats_service.rb
class StatsService
  class UserStats
    attr_accessor(
      :correct,
      :completed,
      :duration,
      :username,
      :remaining,
      :rank,
      :rounds_completed,
    )

    def initialize(correct:, completed:, duration:, username:, remaining:)
      @correct = correct
      @completed = completed
      @duration = duration
      @username = username
      @remaining = remaining
    end

    def percentage
      if @completed > 0
        @correct / @completed.to_f * 100.0
      else
        0
      end
    end

    def total
      completed + remaining
    end
  end

  def initialize(user, game)
    @user = user
    @game = game
  end

  def self.all_user_stats(game, round=nil)
    User.all.map do |user|
      if round.present?
        StatsService.new(user, game).user_round_stats(round)
      else
        StatsService.new(user, game).user_stats
      end
    end.sort do |a, b|
      if a.percentage > b.percentage
        -1
      elsif b.percentage > a.percentage
        1
      else
        a.duration <=> b.duration
      end
    end.each_with_index do |stat, index|
      stat.rank = index + 1
    end.reject do |stat|
      stat.completed == 0
    end
  end

  def user_round_stats(round)
    _format_result(round, _query(round))
  end

  def user_stats
    user_stat = _format_result(nil, _query)
    user_stat.rounds_completed = _rounds_completed

    user_stat
  end

  def _rounds_completed
    sql = <<SQL
    SELECT COUNT(distinct round_id) as count
    FROM questions Q
    INNER JOIN rounds R ON
      Q.round_id = R.id
    LEFT JOIN user_answers A ON
      A.question_id = Q.id
      AND A.user_id = :user_id
    WHERE
      A.id is null
      AND game_id = :game_id
SQL

    query = ActiveRecord::Base.sanitize_sql([
      sql,
      :game_id => @game.id,
      :user_id => @user.id
    ])
    rounds_remaining = ActiveRecord::Base.connection.execute(query)[0]["count"]

    @game.rounds.count - rounds_remaining
  end

  def _format_result(round, result)
    completed = result[0]["completed"] || 0
    remaining = if round.present?
      round.questions.count - completed
    else
      Question.joins(:round).where("rounds.game_id" => @game.id).count - completed
    end

    UserStats.new(
      :username => @user.username,
      :correct => result[0]["correct"] || 0,
      :completed => completed,
      :duration => result[0]["duration"] || 0,
      :remaining => remaining,
    )
  end

  def _query(round=nil)
    sql = <<SQL
      SELECT
        sum(case when A.id is not null then 1 else 0 end) as completed,
        sum(case when correct then 1 else 0 end) as correct,
        AVG(duration) as duration
      FROM questions Q
      INNER JOIN rounds R ON
        Q.round_id = R.id
      INNER JOIN user_answers A ON
        A.question_id = Q.id
      INNER JOIN options O ON
        A.option_id = O.id
      WHERE
        user_id = :user_id
        AND game_id = :game_id
SQL

    if round
      sql += " AND round_id = :round_id"
    end

    query = ActiveRecord::Base.sanitize_sql([
      sql,
      :user_id => @user.id,
      :game_id => @game.id,
      :round_id => round.try(:id)
    ])

    ActiveRecord::Base.connection.execute(query)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  validates_presence_of :username

  has_many :user_answers

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def next_round(game)
    answered_ids = user_answers.map(&:question_id)
    answered_ids = -1 if answered_ids.length == 0
    question = Question
      .joins(:round)
      .where("rounds.game_id = ?", game.id)
      .where("questions.id not in (?)", answered_ids)
      .order("round_id ASC")
      .first

    question.present? ? question.round : nil
  end

  def average_duration
    user_answers.inject(0) { |sum, el| sum + el.duration }.to_f / user_answers.size
  end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :option
  has_one :round, :through => :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_game

  def home
    if signed_in?
      service = StatsService.new(@current_user, @game)
      @stats = StatsService.all_user_stats(@game)
    end
  end

  private

  def set_game
    if params[:game_id]
      @game = Game.find(params[:game_id])
    else
      @game = Game.first!
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def show
    @question = Question.find(params[:id])
    @round = @question.round
    @game = @round.game
    service = StatsService.new(current_user, @game)
    @user_stats = service.user_round_stats(@round)
  end

  def answer
    @question = Question.find(params[:question_id])
    @option = Option.find(params[:answer_id])
    UserAnswer.create!(
      :question => @question,
      :option => @option,
      :user => current_user,
      :duration => params[:duration]
    )
    @round = @question.round
    @game = @round.game
    @next_question = @round.next_question(current_user)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def show
    @round = Round.find(params[:id])
    @game = @round.game

    @stats = StatsService.all_user_stats(@game, @round)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def next_round_link(user)
    next_round = current_user.next_round(@game)
    if next_round
      next_question = next_round.next_question(current_user)
      link_to "Play #{next_round.label} of #{@game.title}", question_path(next_question), data: { turbolinks: false }
    else
      "You have completed all of the rounds."
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/home/home.html.erb
<% if signed_in? %>
  <h1>Leaderboard</h1>

  <p><%= next_round_link(current_user) %></p>
  <p id="other_game">
    <% Game.all.each do |game| %>
      <% if game.id != @game.id %>
        <%= link_to "Try #{game.title}", game_path(game) %>
      <% end %>
    <% end %>
  </p>

  <%= render "shared/results_table" %>

<% else %>
  <h1>Welcome</h1>
  <div id="welcome">
    <%= image_tag(asset_path('question_mark.jpg')) %>
    <p>
      Rules
      <ul>
        <li>10 questions per round</li>
        <li>10 seconds per question</li>
        <li>Multiple Choice</li>
        <li>Highest percentage wins</li>
        <li>Ties broken on time</li>
      </ul>
    </p>
    <p>
      <%= link_to "Sign In", new_user_session_path(:game_id => @game.id) %>
    </p>
    <p>
      <%= link_to  "Sign Up", new_user_registration_path(:game_id => @game.id) %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('question_mark.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <% if Rails.env.development? || current_user.email == "goggin13@gmail.com" %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    <% end %>

    <p class = "notice" ><%= notice %> </p>
    <p class = "alert" ><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/questions/show.html.erb
<div id="score">
  <%= number_to_percentage(@user_stats.percentage, precision: 1) %>
  <hr/>
  <%= @user_stats.correct %> / <%= @user_stats.completed %>
</div>

<h1>
  <%= @round.label %> : <%= @user_stats.completed + 1 %> / <%= @user_stats.total %>
  <div id="result-bar">
    <% @round.answered_questions(current_user).each do |answer| %>
      <div class="result-box <%= answer.option.correct? ? "" : "in" %>correct"> 
      </div>
    <% end %>
    <% (@round.questions.count - @round.answered_questions(current_user).length).times do |i| %>
      <div class="result-box remaining <%= i == 0 ? "current" : "" %>">
      </div>
    <% end %>
  </div>
</h1>

<p id="question">
  <%= @question.prompt %>
</p>

<% if @question.answered?(current_user) %>

  <p><%= next_round_link(current_user) %></p>

  <ul id="answers">
  <% @question.options.each do |option| %>
    <li class="<%= option.correct ? "" : "in"%>correct">
      <%= option.prompt %>
    </li>
  <% end %>
  </ul>

<% else %>

  <ul id="answers">
  <% found = false %>
  <% @question.options.shuffle.each do |option| %>

    <% if !found && !option.correct %>
      <% found = true %>
      <% extra_class = "default-choice" %>
    <% else %>
      <% extra_class = "" %>
    <% end %>

    <li class="option <%= extra_class %>" id="option-<%= option.id %>">
      <%= link_to option.prompt, question_answer_path(question_id: @question.id, answer_id: option.id) %>
    </li>
  <% end %>

  </ul>
<div id="timer"></div>
<% end %>

app/views/rounds/show.html.erb
<h1><%= @round.label %> Results</h1>

<p>
  <%= next_round_link(current_user) %> |
  <%= link_to "Leaderboard", game_path(@game) %>
</p>

<%= render "shared/results_table" %>

app/views/shared/_results_table.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Rank</th>
    <% if @stats.first.try(:rounds_completed) %>
      <th>Rounds Completed</th>
    <% end %>
    <th>Percentage</th>
    <th>Avg Time</th>
  </tr>

  <% @stats.each do |user_stat| %>
    <tr class="user">
      <td class="username">
        <%= user_stat.username %>
      </td>

      <td class="rank">
        <%= user_stat.rank %>
      </td>

      <% if user_stat.rounds_completed %>
        <td class="rounds_completed">
          <%= user_stat.rounds_completed %>
        </td>
      <% end %>

      <td class="percent">
        <%= number_to_percentage(user_stat.percentage, precision: 1) %>
      </td>

      <td class="time">
        <%= user_stat.duration.round(2) %>s
      </td>
    </tr>
  <% end %>

</table>